// @vitest-environment jsdom
import { act, cleanup, fireEvent, render, screen } from "@testing-library/react";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { UpdatePrompt } from "./UpdatePrompt";
const api = vi.hoisted(() => ({ CheckForUpdate: vi.fn(), InstallUpdate: vi.fn(), CancelUpdate: vi.fn(), OpenUpdateReleasePage: vi.fn() }));
const events = vi.hoisted(() => ({ On: vi.fn() }));
const browser = vi.hoisted(() => ({ OpenURL: vi.fn() }));
vi.mock("../lib/api", () => ({ API: api }));
vi.mock("@wailsio/runtime", () => ({ Events: events, Browser: browser }));
let progress: (event: { data: unknown }) => void;
const offer = { available: true, canInstall: true, version: "1.2.3", current: "1.2.2", size: 10000000, notes: "Release notes", usesInstaller: true };
beforeEach(() => {
  Object.values(api).forEach((fn) => fn.mockReset().mockResolvedValue(undefined));
  api.CheckForUpdate.mockResolvedValue(offer);
  browser.OpenURL.mockReset().mockResolvedValue(undefined);
  events.On.mockImplementation((_name, callback) => { progress = callback; return () => {}; });
  HTMLDialogElement.prototype.showModal = function () { this.open = true; };
  HTMLDialogElement.prototype.close = function () { this.open = false; };
});
afterEach(() => { cleanup(); vi.restoreAllMocks(); });
async function mount() { render(<UpdatePrompt />); await act(async () => {}); }
it.each([null, { available: false }, "offline"])("leaves startup unobstructed without an offer: %s", async (value) => {
  if (value === "offline") api.CheckForUpdate.mockRejectedValueOnce(new Error("offline"));
  else api.CheckForUpdate.mockResolvedValueOnce(value);
  await mount();
  expect(screen.queryByRole("dialog")).toBeNull();
});
it("renders GitHub notes immediately as keyboard-readable Markdown without interpreting HTML", async () => {
  const notes = "## What changed\n- Better musical matches\n<img src=x onerror='alert(1)'>\n<script>alert(1)</script>";
  api.CheckForUpdate.mockResolvedValueOnce({ ...offer, notes });
  await mount();
  const region = screen.getByRole("region", { name: "Release notes" });
  expect(screen.getByRole("heading", { name: "What changed", level: 4 })).toBeTruthy();
  expect(region.querySelector("li")?.textContent?.trim()).toBe("Better musical matches");
  expect(region.closest("details")).toBeNull();
  expect(region.querySelector("img,script")).toBeNull();
  expect(region.tabIndex).toBe(0);
  region.focus();
  expect(document.activeElement).toBe(region);
  expect(api.InstallUpdate).not.toHaveBeenCalled();
  fireEvent.click(screen.getByRole("button", { name: "Release page" }));
  await act(async () => {});
  expect(api.OpenUpdateReleasePage).toHaveBeenCalledOnce();
});
it("renders rich release formatting and keeps links in the system browser", async () => {
  api.CheckForUpdate.mockResolvedValueOnce({ ...offer, notes: "# Release\n\n**Better** and *clearer* with `MERT`.\n\n1. First\n2. Second\n\n- [x] Ready\n\n| Pack | Size |\n| --- | --- |\n| MERT | 214 MB |\n\n> Keep your models.\n\n```text\nexample command\n```\n\n[Details](https://github.com/platten/playlistai/releases/tag/v0.12.1)" });
  await mount();
  const region = screen.getByRole("region", { name: "Release notes" });
  expect(region.querySelector("strong")?.textContent).toBe("Better");
  expect(region.querySelector("em")?.textContent).toBe("clearer");
  expect(region.querySelector("code")?.textContent).toBe("MERT");
  expect(region.querySelectorAll("ol li")).toHaveLength(2);
  expect(region.querySelector("pre code")?.textContent).toContain("example command");
  expect(region.querySelector("blockquote")?.textContent).toContain("Keep your models.");
  expect((screen.getByRole("checkbox") as HTMLInputElement).disabled).toBe(true);
  expect(screen.getByRole("cell", { name: "214 MB" })).toBeTruthy();
  fireEvent.click(screen.getByRole("link", { name: "Details" }));
  await act(async () => {});
  expect(browser.OpenURL).toHaveBeenCalledWith("https://github.com/platten/playlistai/releases/tag/v0.12.1");
  expect(api.InstallUpdate).not.toHaveBeenCalled();
  browser.OpenURL.mockRejectedValueOnce(new Error("browser unavailable"));
  fireEvent.click(screen.getByRole("link", { name: "Details" }));
  await act(async () => {});
  expect(screen.getByRole("alert").textContent).toContain("Could not open release-note link");
  expect(screen.getByRole("dialog")).toBeTruthy();
});
it("does not load images or activate unsafe and relative links", async () => {
  api.CheckForUpdate.mockResolvedValueOnce({ ...offer, notes: "![Cover](https://example.com/tracker.png)\n\n[Script](javascript:alert%281%29) [File](file:///C:/private) [Data](data:text/html,test) [Relative](../settings) [Web](https://example.com/notes)\n\n<iframe src='https://example.com'></iframe>" });
  await mount();
  const region = screen.getByRole("region", { name: "Release notes" });
  expect(region.querySelector("img, iframe, script")).toBeNull();
  expect(screen.getByText("Cover")).toBeTruthy();
  expect(screen.getAllByRole("link")).toHaveLength(1);
  expect(screen.getByRole("link").getAttribute("href")).toBe("https://example.com/notes");
  expect(browser.OpenURL).not.toHaveBeenCalled();
});
it.each(["", " \n\t "])("offers the release page when notes are missing: %j", async (notes) => {
  api.CheckForUpdate.mockResolvedValueOnce({ ...offer, notes });
  await mount();
  expect(screen.getByRole("heading", { name: "What’s new" })).toBeTruthy();
  expect(screen.getByText("Release notes are unavailable here. Open the release page on GitHub for details.")).toBeTruthy();
  expect(screen.queryByRole("region", { name: "Release notes" })).toBeNull();
  expect(screen.getByRole("button", { name: "Release page" })).toBeTruthy();
});
it("keeps recovery notices separate when there is no new release", async () => {
  api.CheckForUpdate.mockResolvedValueOnce({ ...offer, available: false, canInstall: false, notes: "", notice: "Previous install failed" });
  await mount();
  expect(screen.getByText("Previous install failed")).toBeTruthy();
  expect(screen.queryByRole("heading", { name: "What’s new" })).toBeNull();
});
it("shows manual update recovery and dismisses notices without losing the offer", async () => {
  api.CheckForUpdate.mockResolvedValueOnce({ ...offer, available: false, canInstall: false, notice: "Previous install failed", reason: "Read-only directory" });
  await mount();
  expect(screen.getByText("Your previous update needs attention")).toBeTruthy();
  expect(screen.queryByRole("button", { name: "Update and restart" })).toBeNull();
  fireEvent.click(screen.getByLabelText("Dismiss error"));
  expect(screen.queryByText("Previous install failed")).toBeNull();
  api.OpenUpdateReleasePage.mockRejectedValueOnce(new Error("browser unavailable"));
  fireEvent.click(screen.getByRole("button", { name: "Release page" }));
  await act(async () => {});
  expect(screen.getByText(/browser unavailable/)).toBeTruthy();
  fireEvent.click(screen.getByLabelText("Dismiss error"));
  fireEvent.click(screen.getByRole("button", { name: "Later" }));
  expect(screen.queryByRole("dialog")).toBeNull();
});
it("keeps an active download open, reports cancellation failures, and permits install retry", async () => {
  let rejectInstall!: (error: unknown) => void;
  api.InstallUpdate.mockReturnValueOnce(new Promise((_yes, no) => { rejectInstall = no; }));
  await mount();
  fireEvent.click(screen.getByRole("button", { name: "Update and restart" }));
  expect(screen.getByRole("region", { name: "Release notes" }).textContent?.trim()).toBe(offer.notes);
  fireEvent(screen.getByRole("dialog"), new Event("cancel", { cancelable: true }));
  expect(screen.getByRole("dialog")).toBeTruthy();
  act(() => progress({ data: { op: "app-update", done: 5000000, total: 10000000, note: "Downloading" } }));
  expect(screen.getByRole("progressbar").getAttribute("aria-valuetext")).toBe("5.0 / 10.0 MB");
  api.CancelUpdate.mockRejectedValueOnce(new Error("cannot cancel"));
  fireEvent.click(screen.getByRole("button", { name: "Cancel download" }));
  await act(async () => {});
  expect(screen.getByText(/cannot cancel/)).toBeTruthy();
  fireEvent.click(screen.getByRole("button", { name: "Cancel download" }));
  await act(async () => rejectInstall(new Error("cancelled")));
  fireEvent.click(screen.getByRole("button", { name: "Retry update" }));
  await act(async () => {});
  act(() => progress({ data: { op: "app-update", done: 0, total: 0, note: "Restarting to install the update" } }));
  expect((screen.getByRole("button", { name: "Cancel download" }) as HTMLButtonElement).disabled).toBe(true);
});
it("contains keyboard focus and allows Escape when idle", async () => {
  api.CheckForUpdate.mockResolvedValueOnce({ ...offer, notes: "" });
  await mount();
  const dialog = screen.getByRole("dialog");
  const buttons = screen.getAllByRole("button");
  vi.spyOn(HTMLElement.prototype, "getClientRects").mockReturnValue([{ width: 1 }] as unknown as DOMRectList);
  buttons[0].focus();
  fireEvent.keyDown(dialog, { key: "Tab", shiftKey: true });
  expect(document.activeElement).toBe(buttons[buttons.length - 1]);
  fireEvent.keyDown(dialog, { key: "Tab" });
  expect(document.activeElement).toBe(buttons[0]);
  fireEvent.keyDown(dialog, { key: "ArrowDown" });
  fireEvent(dialog, new Event("cancel", { cancelable: true }));
  expect(screen.queryByRole("dialog")).toBeNull();
});
