package nlu

import (
	"context"
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"reflect"
	"testing"
	"time"
)

type parityCase struct {
	Text string `json:"text"`
	Encoding
	Embedding []float32 `json:"embedding,omitempty"`
	Millis    float64   `json:"millis,omitempty"`
}

type parityReport struct {
	Version    int          `json:"version"`
	Kind       ModelKind    `json:"kind"`
	Source     string       `json:"source"`
	MaxTokens  int          `json:"maxTokens"`
	Cases      []parityCase `json:"cases"`
	LoadMillis float64      `json:"loadMillis,omitempty"`
}

// The reference is independently generated by Hugging Face's tokenizer and
// original PyTorch MiniLM. It is never regenerated by native code to make a
// failure disappear. Downloads and Python are not needed for normal tests.
func TestNativeReferenceParity(t *testing.T) {
	referenceDir := os.Getenv("PLAYLISTAI_TEST_NLU_PARITY_DIR")
	if referenceDir == "" {
		t.Skip("set PLAYLISTAI_TEST_NLU_PARITY_DIR for original-model parity")
	}
	for _, kind := range []ModelKind{MiniLM, DistilBERT} {
		t.Run(string(kind), func(t *testing.T) {
			raw, err := os.ReadFile(filepath.Join(referenceDir, string(kind)+"-reference.json"))
			if err != nil {
				t.Fatal(err)
			}
			var reference parityReport
			if err = json.Unmarshal(raw, &reference); err != nil {
				t.Fatal(err)
			}
			if reference.Version != 1 || reference.Kind != kind || len(reference.Cases) == 0 {
				t.Fatal("invalid parity fixture")
			}
			tokenizer, err := LoadWordPiece(filepath.Join(reference.Source, "vocab.txt"), kind == MiniLM, reference.MaxTokens)
			if err != nil {
				t.Fatal(err)
			}
			actual := parityReport{Version: 1, Kind: kind, Source: reference.Source, MaxTokens: reference.MaxTokens}
			var worker *Worker
			if kind == MiniLM {
				dir, library := os.Getenv("PLAYLISTAI_TEST_NLU_MODEL_DIR"), os.Getenv("PLAYLISTAI_TEST_NLU_RUNTIME")
				if dir == "" || library == "" {
					t.Fatal("native MiniLM parity requires model and runtime paths")
				}
				worker = &Worker{Config: WorkerConfig{Kind: kind, ModelDir: dir, RuntimeLibrary: library}}
				defer worker.Close()
				started := time.Now()
				if err = worker.Health(context.Background()); err != nil {
					t.Fatal(err)
				}
				actual.LoadMillis = float64(time.Since(started).Microseconds()) / 1000
			}
			for _, expected := range reference.Cases {
				started := time.Now()
				encoding, err := tokenizer.Encode(expected.Text)
				if err != nil {
					t.Fatal(err)
				}
				row := parityCase{Text: expected.Text, Encoding: encoding}
				if !reflect.DeepEqual(encoding, expected.Encoding) {
					t.Errorf("tokenizer mismatch for %q\nactual %+v\nexpected %+v", expected.Text, encoding, expected.Encoding)
				}
				if worker != nil {
					row.Embedding, err = worker.EmbedText(context.Background(), expected.Text)
					if err != nil {
						t.Fatal(err)
					}
					if len(expected.Embedding) != EmbeddingDimension {
						t.Fatal("missing independent reference vector")
					}
					var cosine, maxError float64
					for i, v := range row.Embedding {
						cosine += float64(v) * float64(expected.Embedding[i])
						maxError = math.Max(maxError, math.Abs(float64(v)-float64(expected.Embedding[i])))
					}
					if cosine < 0.99999 || maxError > 0.001 {
						t.Errorf("embedding parity for %q: cosine=%f maxError=%f", expected.Text, cosine, maxError)
					}
				}
				row.Millis = float64(time.Since(started).Microseconds()) / 1000
				actual.Cases = append(actual.Cases, row)
			}
			if outputDir := os.Getenv("PLAYLISTAI_TEST_NLU_PARITY_OUTPUT"); outputDir != "" {
				if err := os.MkdirAll(outputDir, 0700); err != nil {
					t.Fatal(err)
				}
				data, err := json.MarshalIndent(actual, "", "  ")
				if err != nil {
					t.Fatal(err)
				}
				if err = os.WriteFile(filepath.Join(outputDir, string(kind)+"-native.json"), data, 0600); err != nil {
					t.Fatal(err)
				}
			}
		})
	}
}

func TestNativeBaseDistilBERTAbstains(t *testing.T) {
	dir := os.Getenv("PLAYLISTAI_TEST_NLU_DISTILBERT_DIR")
	if dir == "" {
		t.Skip("set PLAYLISTAI_TEST_NLU_DISTILBERT_DIR for real base-artifact abstention")
	}
	library := os.Getenv("PLAYLISTAI_TEST_NLU_RUNTIME")
	w := &Worker{Config: WorkerConfig{Kind: DistilBERT, ModelDir: dir, RuntimeLibrary: library}}
	defer w.Close()
	result, err := w.Propose(context.Background(), "Only Aerosmith. Include Hurt by Nine Inch Nails.")
	if err != nil {
		t.Fatal(err)
	}
	if !result.Abstained || result.Reason != "trained_head_unavailable" || len(result.Proposals) != 0 {
		t.Fatalf("base encoder guessed musical intent: %+v", result)
	}
}
