package schema

var legacyExamples = []Example{
	{
		Prompt: "upbeat instrumental tracks like Justice, about 25 songs, a little unpredictable",
		JSON:   `{"genre_expansions":[],"references":[{"kind":"artist","value":"Justice","influence":"positive","explicit":true,"span":"Justice"}],"inferred_anchors":[],"required_tracks":[],"essential_criteria":[],"styles":[],"moods":[{"value":"upbeat","influence":"positive","explicit":true,"span":"upbeat"}],"instrumentation":[{"value":"instrumental","influence":"positive","explicit":true,"span":"instrumental"}],"vocal_preference":{"value":"instrumental","influence":"positive","explicit":true,"span":"instrumental"},"textures":[],"hard_constraints":[],"unsupported_requirements":[],"mode":"similar","journey_waypoints":[],"energy_trajectory":[],"total_count":25,"audio_weight":0.5,"cooccurrence_weight":0.5,"discovery":0.35,"artist_diversity":0.7,"transition_smoothness":0.5,"notes":"Use the explicitly named Justice reference; upbeat and instrumental remain preserved preferences."}`,
	},
	{
		Prompt: "a 12-track journey from Nick Drake to Aphex Twin via Radiohead",
		JSON:   `{"genre_expansions":[],"references":[{"kind":"artist","value":"Nick Drake","influence":"positive","explicit":true,"span":"Nick Drake"},{"kind":"artist","value":"Radiohead","influence":"positive","explicit":true,"span":"Radiohead"},{"kind":"artist","value":"Aphex Twin","influence":"positive","explicit":true,"span":"Aphex Twin"}],"inferred_anchors":[],"required_tracks":[],"essential_criteria":[],"styles":[],"moods":[],"instrumentation":[],"vocal_preference":{"value":"","influence":"positive","explicit":false,"span":""},"textures":[],"hard_constraints":[],"unsupported_requirements":[],"mode":"journey","journey_waypoints":[{"kind":"artist","value":"Nick Drake","influence":"positive","explicit":true,"span":"Nick Drake"},{"kind":"artist","value":"Radiohead","influence":"positive","explicit":true,"span":"Radiohead"},{"kind":"artist","value":"Aphex Twin","influence":"positive","explicit":true,"span":"Aphex Twin"}],"energy_trajectory":[],"total_count":12,"audio_weight":0.5,"cooccurrence_weight":0.5,"discovery":0.1,"artist_diversity":0.7,"transition_smoothness":0.8,"notes":"A smooth twelve-track journey through the explicitly named artists."}`,
	},
	{
		Prompt: "ambient electronic with microdetail, a deep groove, occasional sparkle, relaxing but not sleepy, no abstract drone",
		JSON:   `{"genre_expansions":[],"references":[],"inferred_anchors":[{"kind":"track","value":"Four Tet - Two Thousand and Seventeen","role":"rhythmic electronic anchor","reason":"connects ambient electronic texture with a grounded groove","span":"ambient electronic with microdetail, a deep groove"},{"kind":"track","value":"Boards of Canada - Roygbiv","role":"textural electronic anchor","reason":"complements detailed, relaxing electronic texture","span":"ambient electronic with microdetail"}],"required_tracks":[],"essential_criteria":[{"kind":"style","value":"ambient electronic","scope":"playlist","span":"ambient electronic"}],"styles":[{"value":"ambient electronic","influence":"positive","explicit":true,"span":"ambient electronic"},{"value":"abstract drone","influence":"negative","explicit":true,"span":"no abstract drone"}],"moods":[{"value":"relaxing","influence":"positive","explicit":true,"span":"relaxing"},{"value":"sleepy","influence":"negative","explicit":true,"span":"not sleepy"}],"instrumentation":[],"vocal_preference":{"value":"","influence":"positive","explicit":false,"span":""},"textures":[{"value":"microdetail","influence":"positive","explicit":true,"span":"microdetail"},{"value":"a deep groove","influence":"positive","explicit":true,"span":"a deep groove"},{"value":"occasional sparkle","influence":"positive","explicit":true,"span":"occasional sparkle"}],"hard_constraints":[{"kind":"exclude_style","value":"abstract drone","span":"no abstract drone"}],"unsupported_requirements":[{"text":"no abstract drone","reason":"requires complete grounded style evidence for each selected track","span":"no abstract drone"}],"mode":"similar","journey_waypoints":[],"energy_trajectory":[],"total_count":20,"audio_weight":0.7,"cooccurrence_weight":0.3,"discovery":0.2,"artist_diversity":0.7,"transition_smoothness":0.7,"notes":"Ambient electronic is essential. Inferred anchors require catalog resolution and musical-suitability validation."}`,
	},
	{
		Prompt: "electronic music",
		JSON:   `{"genre_expansions":[],"references":[],"inferred_anchors":[{"kind":"track","value":"Kraftwerk - The Robots","role":"foundational electronic anchor","reason":"provides a broad electronic retrieval starting point","span":"electronic music"},{"kind":"track","value":"The Chemical Brothers - Star Guitar","role":"rhythmic electronic anchor","reason":"broadens electronic retrieval without changing the requested category","span":"electronic music"}],"required_tracks":[],"essential_criteria":[{"kind":"style","value":"electronic","scope":"playlist","span":"electronic"}],"styles":[{"value":"electronic","influence":"positive","explicit":true,"span":"electronic"}],"moods":[],"instrumentation":[],"vocal_preference":{"value":"","influence":"positive","explicit":false,"span":""},"textures":[],"hard_constraints":[],"unsupported_requirements":[],"mode":"similar","journey_waypoints":[],"energy_trajectory":[],"total_count":20,"audio_weight":0.5,"cooccurrence_weight":0.5,"discovery":0.1,"artist_diversity":0.7,"transition_smoothness":0.5,"notes":"Electronic is the essential musical category; inferred anchors are retrieval proposals only."}`,
	},
}
