package schema

const SystemPrompt = `You translate a music request into the exact JSON intent contract shown by the examples.
Preserve the user's meaning and wording. Never turn a genre, mood, activity, or other musical category into an artist reference.
"references" contains only artists or tracks the user actually names. Set explicit=true and copy supporting user words into span. Never invent an explicit reference.
"inferred_anchors" contains zero to three complementary artist or track proposals that may help retrieval when the user named no reference. Give each a distinct role and a concise musical reason. Anchors are proposals, not user instructions or proof that tracks meet a genre.
"essential_criteria" contains defining musical categories whose absence would make the result fail the request. A simple genre request such as "electronic music" makes electronic an essential style. Ordinary adjectives remain soft preferences. Preserve deliberate hybrids such as "electronic with some rock influence" by making electronic essential and rock a soft preference. For a category journey, use journey_start, journey_via, and journey_end scopes rather than requiring every track to match every category.
Only tracks the user explicitly requires belong in "required_tracks". Required tracks remain distinct from references and inferred anchors.
Styles, moods, instrumentation, vocal preference, and textures preserve positive and negative soft preferences.
Supported always-on hard constraints are exclude_artist, exclude_reference_artists, and no_back_to_back_artist. Put other strict demands in hard_constraints and describe the evidence requirement in unsupported_requirements; do not claim enforcement.
Use journey_waypoints only for artist or track entities the user names. Energy trajectory points use positions and energies from 0 to 1.
total_count is total output tracks, including required tracks. audio_weight and cooccurrence_weight independently express sound versus playlist-context similarity. discovery, artist_diversity, and transition_smoothness are independent 0..1 controls.
Use an empty vocal preference object with empty strings, false, and empty span when unspecified.
Reply with ONLY the JSON object.`

type Example struct {
	Prompt string
	JSON   string
}

var FewShot = []Example{
	{
		Prompt: "upbeat instrumental tracks like Justice, about 25 songs, a little unpredictable",
		JSON:   `{"references":[{"kind":"artist","value":"Justice","influence":"positive","explicit":true,"span":"Justice"}],"inferred_anchors":[],"required_tracks":[],"essential_criteria":[],"styles":[],"moods":[{"value":"upbeat","influence":"positive","explicit":true,"span":"upbeat"}],"instrumentation":[{"value":"instrumental","influence":"positive","explicit":true,"span":"instrumental"}],"vocal_preference":{"value":"instrumental","influence":"positive","explicit":true,"span":"instrumental"},"textures":[],"hard_constraints":[],"unsupported_requirements":[],"mode":"similar","journey_waypoints":[],"energy_trajectory":[],"total_count":25,"audio_weight":0.5,"cooccurrence_weight":0.5,"discovery":0.35,"artist_diversity":0.7,"transition_smoothness":0.5,"notes":"Use the explicitly named Justice reference; upbeat and instrumental remain preserved preferences."}`,
	},
	{
		Prompt: "a 12-track journey from Nick Drake to Aphex Twin via Radiohead",
		JSON:   `{"references":[{"kind":"artist","value":"Nick Drake","influence":"positive","explicit":true,"span":"Nick Drake"},{"kind":"artist","value":"Radiohead","influence":"positive","explicit":true,"span":"Radiohead"},{"kind":"artist","value":"Aphex Twin","influence":"positive","explicit":true,"span":"Aphex Twin"}],"inferred_anchors":[],"required_tracks":[],"essential_criteria":[],"styles":[],"moods":[],"instrumentation":[],"vocal_preference":{"value":"","influence":"positive","explicit":false,"span":""},"textures":[],"hard_constraints":[],"unsupported_requirements":[],"mode":"journey","journey_waypoints":[{"kind":"artist","value":"Nick Drake","influence":"positive","explicit":true,"span":"Nick Drake"},{"kind":"artist","value":"Radiohead","influence":"positive","explicit":true,"span":"Radiohead"},{"kind":"artist","value":"Aphex Twin","influence":"positive","explicit":true,"span":"Aphex Twin"}],"energy_trajectory":[],"total_count":12,"audio_weight":0.5,"cooccurrence_weight":0.5,"discovery":0.1,"artist_diversity":0.7,"transition_smoothness":0.8,"notes":"A smooth twelve-track journey through the explicitly named artists."}`,
	},
	{
		Prompt: "ambient electronic with microdetail, a deep groove, occasional sparkle, relaxing but not sleepy, no abstract drone",
		JSON:   `{"references":[],"inferred_anchors":[{"kind":"artist","value":"Four Tet","role":"rhythmic electronic anchor","reason":"connects ambient electronic texture with a grounded groove","span":"ambient electronic with microdetail, a deep groove"},{"kind":"artist","value":"Boards of Canada","role":"textural electronic anchor","reason":"complements detailed, relaxing electronic texture","span":"ambient electronic with microdetail"}],"required_tracks":[],"essential_criteria":[{"kind":"style","value":"ambient electronic","scope":"playlist","span":"ambient electronic"}],"styles":[{"value":"ambient electronic","influence":"positive","explicit":true,"span":"ambient electronic"},{"value":"abstract drone","influence":"negative","explicit":true,"span":"no abstract drone"}],"moods":[{"value":"relaxing","influence":"positive","explicit":true,"span":"relaxing"},{"value":"sleepy","influence":"negative","explicit":true,"span":"not sleepy"}],"instrumentation":[],"vocal_preference":{"value":"","influence":"positive","explicit":false,"span":""},"textures":[{"value":"microdetail","influence":"positive","explicit":true,"span":"microdetail"},{"value":"a deep groove","influence":"positive","explicit":true,"span":"a deep groove"},{"value":"occasional sparkle","influence":"positive","explicit":true,"span":"occasional sparkle"}],"hard_constraints":[{"kind":"exclude_style","value":"abstract drone","span":"no abstract drone"}],"unsupported_requirements":[{"text":"no abstract drone","reason":"requires complete grounded style evidence for each selected track","span":"no abstract drone"}],"mode":"similar","journey_waypoints":[],"energy_trajectory":[],"total_count":20,"audio_weight":0.7,"cooccurrence_weight":0.3,"discovery":0.2,"artist_diversity":0.7,"transition_smoothness":0.7,"notes":"Ambient electronic is essential. Inferred anchors require catalog resolution and musical-suitability validation."}`,
	},
	{
		Prompt: "electronic music",
		JSON:   `{"references":[],"inferred_anchors":[{"kind":"artist","value":"Kraftwerk","role":"foundational electronic anchor","reason":"provides a broad electronic retrieval starting point","span":"electronic music"},{"kind":"artist","value":"The Chemical Brothers","role":"rhythmic electronic anchor","reason":"broadens electronic retrieval without changing the requested category","span":"electronic music"}],"required_tracks":[],"essential_criteria":[{"kind":"style","value":"electronic","scope":"playlist","span":"electronic"}],"styles":[{"value":"electronic","influence":"positive","explicit":true,"span":"electronic"}],"moods":[],"instrumentation":[],"vocal_preference":{"value":"","influence":"positive","explicit":false,"span":""},"textures":[],"hard_constraints":[],"unsupported_requirements":[],"mode":"similar","journey_waypoints":[],"energy_trajectory":[],"total_count":20,"audio_weight":0.5,"cooccurrence_weight":0.5,"discovery":0.1,"artist_diversity":0.7,"transition_smoothness":0.5,"notes":"Electronic is the essential musical category; inferred anchors are retrieval proposals only."}`,
	},
}
