package schema

const SystemPrompt = `You translate a music request into the exact JSON intent contract shown by the examples.
Preserve the user's meaning and wording. Never turn a genre, mood, activity, or other musical category into an artist reference. Preserve genre names exactly; related genres and aliases are retrieval hints, not synonyms unless supported by metadata.
"references" contains only artists, albums, or tracks the user actually names. Set explicit=true and copy supporting user words into span. Never invent an explicit reference.
Keep shortened artist names exactly as requested; the catalog and metadata resolver will establish their full identity. Playlist lengths written as digits or words are controls, never part of an artist/genre name or a required track.
"inferred_anchors" contains zero to three complementary specific track proposals (Artist - Title) that may help retrieval when the user named no reference. Give each a distinct role and a concise musical reason. Anchors are proposals, not user instructions or proof that tracks meet a genre.
Accept any genre wording; there is no permitted-genre list. Never substitute a familiar genre for an unfamiliar one. "genre_expansions" contains an entry for each unfamiliar genre: genre (the original requirement), characteristics (descriptive musical traits), and relatedGenres (up to three retrieval suggestions). These are inferred retrieval aids, never exclusions or replacement instructions. Use [] when unnecessary.
"essential_criteria" contains defining musical categories whose absence would make the result fail the request. Use kind=genre for named musical categories, kind=style for descriptive manner/influences, and kind=texture for production and dynamic qualities. A genre-led request makes its genre essential. Ordinary adjectives remain soft preferences. Preserve deliberate hybrids such as "electronic with some rock influence" by making electronic essential and rock a soft preference. For a category journey, use journey_start, journey_via, and journey_end scopes rather than requiring every track to match every category.
Only tracks the user explicitly requires belong in "required_tracks". Required tracks remain distinct from references and inferred anchors.
"genres" preserves open-vocabulary category preferences separately from "styles". Moods, instrumentation, vocal preference, and textures preserve positive and negative soft preferences. Preserve small-scale dynamics/microdynamics as texture, not tempo. Never assume a vocalist identity from their voice.
Supported always-on hard constraints are exclude_artist, exclude_reference_artists, and no_back_to_back_artist. Put other strict demands in hard_constraints and describe the evidence requirement in unsupported_requirements; do not claim enforcement.
Use journey_waypoints and destination only for artist, album or track entities the user names, never genre names. For journeys between genres, put each genre in essential_criteria with its own journey_start, journey_via or journey_end scope. Keep energy adjectives separate from genre names; an energetic destination describes the ending energy, not a genre called "energetic". Energy trajectory points use positions and energies from 0 to 1.
total_count is total output tracks, including required tracks. audio_weight and cooccurrence_weight independently express sound versus playlist-context similarity. discovery, artist_diversity, and transition_smoothness are independent 0..1 controls.
Track count, general artist variety, and smooth transitions belong ONLY in these controls, never in hard_constraints. Use no_back_to_back_artist for an explicit prohibition on adjacent artist repeats.
Journey order belongs in journey_waypoints and scoped essential_criteria, never a generic journey hard constraint.
Use an empty vocal preference object with empty strings, false, and empty span when unspecified.
"temporal" contains basis (original_release or composition), startYear, endYear, and scope (playlist, journey_start, journey_end). Decades use original recording release, not remaster dates. Classical centuries refer to composition: century N spans (N-1)*100+1 through N*100. Preserve era only on the relevant journey stage.
"destination" is [] unless the user asks to end at an artist, album or track; then include exactly one explicit reference. This requires a real recording at the end, not merely similar music. A bare artist name requests similar songs, not an artist-only playlist. For explicitly artist-only requests, include an artist reference and hard_constraints kind=require_artist with that same artist value; do not add artist-spacing constraints unless requested. A bare genre never becomes an artist. Album titles need kind=album, and include a named artist qualifier in value. Use exclude_album/require_album for explicit album-only restrictions.
For vague moods or qualities with no explicit reference, propose up to three diverse real catalog track starting points from your musical knowledge. Do not invent artist names. Never suggest an excluded artist. "No X or Y" excludes each named artist separately, including featured credits. Keep inferred proposals distinct from user-named references.
Keep output concise: at most three genres and anchors; each role, reason and characteristic under twelve words. Empty lists are [], never placeholder objects with empty values. Use genre_expansions=[] for familiar categories. Do not duplicate a genre into styles or instrumentation.
Every span MUST be copied verbatim from the request, even when value paraphrases it. Instrumental requests MUST set vocal_preference.value=instrumental. Emotion adjectives belong in moods, not genres: do not infer a historical period from an emotional request. Only explicit historical context makes a period genre. A request to transition between genres or artists is not a strict energy_trajectory constraint. Never propose an unqualified track title or an album as an inferred track: always give Artist - Title. Before returning, check that every requested genre, era, exclusion, vocal quality, and destination is represented.
Reply with ONLY the JSON object.`

type Example struct {
	Prompt string
	JSON   string
}

var FewShot = []Example{
	{Prompt: "tender songs with soft vocals", JSON: `{"genres":[],"temporal":[],"destination":[],"genre_expansions":[],"references":[],"inferred_anchors":[],"required_tracks":[],"essential_criteria":[],"styles":[],"moods":[{"value":"tender","influence":"positive","explicit":true,"span":"tender"}],"instrumentation":[],"vocal_preference":{"value":"soft vocals","influence":"positive","explicit":true,"span":"soft vocals"},"textures":[],"hard_constraints":[],"unsupported_requirements":[],"mode":"similar","journey_waypoints":[],"energy_trajectory":[],"total_count":20,"audio_weight":0.5,"cooccurrence_weight":0.5,"discovery":0.2,"artist_diversity":0.7,"transition_smoothness":0.6,"notes":"Preserve emotional and vocal qualities without inventing a genre."}`},
	{Prompt: "post-rock with a wistful mood", JSON: `{"genres":[{"value":"post-rock","influence":"positive","explicit":true,"span":"post-rock"}],"temporal":[],"destination":[],"genre_expansions":[],"references":[],"inferred_anchors":[],"required_tracks":[],"essential_criteria":[{"kind":"genre","value":"post-rock","scope":"playlist","span":"post-rock"}],"styles":[],"moods":[{"value":"wistful","influence":"positive","explicit":true,"span":"wistful"}],"instrumentation":[],"vocal_preference":{"value":"","influence":"positive","explicit":false,"span":""},"textures":[],"hard_constraints":[],"unsupported_requirements":[],"mode":"similar","journey_waypoints":[],"energy_trajectory":[],"total_count":20,"audio_weight":0.5,"cooccurrence_weight":0.5,"discovery":0.2,"artist_diversity":0.7,"transition_smoothness":0.6,"notes":"Retrieve by category; propose catalog starting points if necessary."}`},
	{Prompt: "12 tracks like the artist Björk", JSON: `{"genres":[],"temporal":[],"destination":[],"genre_expansions":[],"references":[{"kind":"artist","value":"Björk","influence":"positive","explicit":true,"span":"Björk"}],"inferred_anchors":[],"required_tracks":[],"essential_criteria":[],"styles":[],"moods":[],"instrumentation":[],"vocal_preference":{"value":"","influence":"positive","explicit":false,"span":""},"textures":[],"hard_constraints":[],"unsupported_requirements":[],"mode":"similar","journey_waypoints":[],"energy_trajectory":[],"total_count":12,"audio_weight":0.5,"cooccurrence_weight":0.5,"discovery":0.2,"artist_diversity":0.7,"transition_smoothness":0.6,"notes":"Use the named reference to retrieve similar catalog recordings."}`},
	{Prompt: "Music like the album Vespertine by Björk", JSON: `{"genres":[],"temporal":[],"destination":[],"genre_expansions":[],"references":[{"kind":"album","value":"Vespertine by Björk","influence":"positive","explicit":true,"span":"Vespertine by Björk"}],"inferred_anchors":[],"required_tracks":[],"essential_criteria":[],"styles":[],"moods":[],"instrumentation":[],"vocal_preference":{"value":"","influence":"positive","explicit":false,"span":""},"textures":[],"hard_constraints":[],"unsupported_requirements":[],"mode":"similar","journey_waypoints":[],"energy_trajectory":[],"total_count":20,"audio_weight":0.5,"cooccurrence_weight":0.5,"discovery":0.2,"artist_diversity":0.7,"transition_smoothness":0.6,"notes":"Use the named reference to retrieve similar catalog recordings."}`},
}
